# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

org.gradle.parallel=true
org.gradle.configuration-cache=false


# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3

# Mod Properties
mod_version = 1.0.0
maven_group = com.tantaihaha.forcechunkloading
archives_base_name = force_chunk_loading

# Dependencies
# check this on https://fabricmc.net/develop
fabric_version=0.155.2+26.1.2

